/* ------------------------------------------------------------------
   PMBOK 8th Edition Prep — pack config.

   A study pack for project managers preparing for the PMP exam (or
   any PMBOK 8e knowledge check). Tone is exam-prep, not aspirational
   leadership coaching: short principles, named processes, definite
   answers to scenario MCQs. Content is paraphrased from the 2025
   PMBOK® Guide and Standard for Project Management — PMI's wording
   is not reproduced. PMBOK and PMP are trademarks of PMI.
------------------------------------------------------------------ */

import type { PackConfig } from "./_types";
import { ICON_SVG, ICON_MASKABLE_SVG } from "./icons";

export const packConfig: PackConfig = {
  id: "pmbok-prep",
  name: "PMBOK 8e Prep",
  shortName: "PMBOK",
  tagline: "Six principles, five focus areas, seven domains — exam-ready",
  description:
    "Study pack for the PMBOK Guide 8th Edition (2025). Covers the six refined principles, the five focus areas (formerly Process Groups), the seven Performance Domains (Governance, Scope, Schedule, Finance, Stakeholders, Resources, Risk), tailoring, and exam strategy. Includes flashcards, quizzes, games, section tests, and a 30-question mock exam. Progress is saved locally in your browser.",
  url: "https://lms-hobby.vercel.app",
  author: "cca-f-prep",
  nav: [
    { label: "Home", href: "/", icon: "home", mobile: true, match: ["/"] },
    {
      label: "Sections",
      href: "/#sections",
      icon: "layers",
      mobile: true,
      match: ["/section"],
    },
    {
      label: "Mock exam",
      href: "/mock",
      icon: "award",
      mobile: true,
      match: ["/mock"],
    },
    {
      label: "Progress",
      href: "/#progress",
      icon: "trending-up",
      mobile: true,
      match: [],
    },
  ],
  askAI: {
    projectUrl: "",
    fallbackUrl: "https://claude.ai/new",
    heading: "Ask a PMBOK tutor",
    description:
      "Paste this lesson plus your question into a fresh chat. Claude is a strong PMP study coach — try asking for additional worked examples, a comparison across PMBOK editions (6e vs 7e vs 8e), or a tougher scenario.",
  },
  copy: {
    mockExamsHeading: "Practice exams",
    mockExamsBlurb:
      "Full-length, timed practice exams in the PMP scenario style. Each question explains the principle behind the right answer.",
    mockExamsMetaDescription:
      "30-question scenario-style practice exam covering all six PMBOK 8e principles, five focus areas, and seven performance domains.",
    sectionTestSingular: "Module quiz",
    conceptsMasteredLabel: "Lessons mastered",
    sectionsCompleteLabel: "Modules complete",
    bestMockScoreLabel: "Best practice exam score",
    studyStreakLabel: "Study streak",
    recoDrillLabel: "Practice",
    recoDrillTitle: "Re-try a tricky lesson",
    recoSectionTestLabel: "Module quiz",
    recoSectionTestTitle: "Module quiz ready",
    recoLessonLabel: "Continue — next lesson",
    recoLessonTitle: "Read the next lesson",
    recoQuizLabel: "Continue — quick check",
    recoQuizTitle: "Quick lesson check",
    recoDoneLabel: "All caught up",
    recoDoneTitle: "Practice-exam ready",
    recoDoneMessage:
      "You've worked through every lesson. Sit a full practice exam under timed conditions and treat anything below 70% as a study gap.",
    whatYoullLearnHeading: "What you'll be able to do",
    passLabel: "pass",
    belowPassGateLabel: "below pass gate",
    courseSingular: "Course",
    coursePlural: "Courses",
    moduleSingular: "Module",
    modulePlural: "Modules",
    lessonSingular: "Lesson",
    lessonPlural: "Lessons",
  },
  masteryLevels: [
    { label: "Not started", tone: "neutral" },
    { label: "Read the lesson", tone: "neutral" },
    {
      label: "Try again",
      minScorePct: 0,
      isUnderwhelm: true,
      tone: "warn",
    },
    {
      label: "Practiced",
      minScorePct: 0.6,
      countsAsMastered: true,
      tone: "good",
    },
    {
      label: "Mastered",
      minScorePct: 0.9,
      countsAsMastered: true,
      tone: "good",
    },
  ],
  manifest: {
    backgroundColor: "#0e1d3a",
    themeColor: "#0e1d3a",
    categories: ["education", "business", "productivity"],
  },
  theme: {
    light: {
      "--canvas": "#f6f8fc",
      "--panel": "#ffffff",
      "--panel-2": "#eaeef7",
      "--border": "#d3dbeb",
      "--ink": "#0e1d3a",
      "--muted": "#566481",
      "--accent": "#1a3e8f",
      "--accent-2": "#3f6dca",
      "--good": "#2f7a4a",
      "--bad": "#b53a3a",
      "--warn": "#a8862c",
    },
    dark: {
      "--canvas": "#0a142b",
      "--panel": "#11203f",
      "--panel-2": "#162a52",
      "--border": "#28406e",
      "--ink": "#e6ecf7",
      "--muted": "#a4b1cd",
      "--accent": "#7aa0e8",
      "--accent-2": "#f0b952",
      "--good": "#7ec48b",
      "--bad": "#dd8484",
      "--warn": "#e3c97a",
    },
  },
  iconSvg: ICON_SVG,
  iconMaskableSvg: ICON_MASKABLE_SVG,
  // Generated by .github/workflows/generate-images-on-prompts.yml.
  // Until the workflow has run, the picker falls back to iconSvg
  // and the course page omits the hero. After the workflow lands
  // images in web/public/images/, both surfaces light up.
  heroImagePath: "/images/hero/final/pmbok-course-hero.jpg",
  prerequisites: {
    heading: "Before you begin",
    intro:
      "This journey prepares you for the Project Management Professional (PMP)® exam based on PMI's PMBOK Guide 8th Edition (2025). It's content prep — not a substitute for PMI's eligibility checks. Make sure you (or your audit-readiness file) clear the gates below before you book the test.",
    requirements: [
      {
        label: "35 contact hours of project-management education",
        detail:
          "Required by PMI for application approval. A separate accredited course (in person, online, or self-paced) typically satisfies this — this study pack does NOT count toward the 35 hours on its own.",
      },
      {
        label:
          "Experience: 36 months leading projects (with a four-year degree) OR 60 months without one",
        detail:
          "Months may be non-consecutive but must be within the last 8 years. CAPM® candidates have lighter requirements; this pack is sized for PMP.",
      },
      {
        label: "An active PMI account + application submitted",
        detail:
          "Apply at pmi.org. The application closes audit-readiness — be prepared to provide signed verification from supervisors for ~5 of your listed projects if randomly audited.",
      },
      {
        label: "Comfort with English-language scenario reading",
        detail:
          "The exam runs in many languages but the canonical test is English. Long scenario stems (100+ words) are common — fast reading helps.",
      },
    ],
    assumptions: [
      {
        label: "Roughly 60–80 hours of study time over 6–10 weeks",
        detail:
          "Most candidates report 50–100 hours total prep. This journey is sized to fit inside that range when paired with two full mock exams and targeted weak-spot drilling.",
      },
      {
        label: "Exam fee: ~US $405 (PMI member) or ~US $555 (non-member)",
        detail:
          "PMI membership is ~US $159/year and includes a free PMBOK Guide PDF — it usually pays for itself versus the non-member exam fee.",
      },
      {
        label: "Test format: 180 questions, 230 minutes, online-proctored or test-centre",
        detail:
          "Two optional 10-minute breaks. Three performance domains (People 42%, Process 50%, Business Environment 8%) — note the domain weights differ from PMBOK 8e content weights.",
      },
    ],
    externalLinks: [
      {
        label: "PMI · PMP exam page",
        href: "https://www.pmi.org/certifications/project-management-pmp",
      },
      {
        label: "PMI · PMP Exam Content Outline (PDF)",
        href: "https://www.pmi.org/-/media/pmi/documents/public/pdf/certifications/pmp-examination-content-outline.pdf",
      },
      {
        label: "PMI · PMBOK Guide 8th Edition",
        href: "https://www.pmi.org/standards/pmbok",
      },
    ],
    notForYouIf: [
      "You're brand-new to project work with no leadership exposure — PMI's experience gates will block you. Consider CAPM® first.",
      "You only need a quick overview of PMBOK 8e without sitting the PMP — you'll still get value, but the exam-strategy section will read as overkill.",
      "You're studying for a different certification (PRINCE2, IPMA, ITIL) — vocabulary overlaps but PMI's preferred-answer patterns are distinct and may mislead you on those exams.",
    ],
  },
};
